// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoleRollsPocketEdition.Infrastructure;

#nullable disable

namespace RoleRollsPocketEdition.Migrations
{
    [DbContext(typeof(RoleRollsDbContext))]
    [Migration("20250208160814_fdfdf")]
    partial class fdfdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Archetypes.Archetype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.ToTable("Archetypes");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Bonuses.Bonus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchetypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchetypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Bonus");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Campaigns.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitationSecret")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignTemplateId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Campaigns.Entities.CampaignPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvidationCode")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignPlayers");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Core.Authentication.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Attribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributeTemplateId");

                    b.HasIndex("CreatureId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Creature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatureTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Creatures");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.CreaturePower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsumedUsages")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PowerTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("PowerTemplateId");

                    b.ToTable("CreaturePowers");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Defense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefenseTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("DefenseTemplateId");

                    b.ToTable("Defenses");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArmsId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FeetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HandsId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeftRingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MainHandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NeckId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OffHandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RightRingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WaistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArmsId")
                        .IsUnique();

                    b.HasIndex("ChestId")
                        .IsUnique();

                    b.HasIndex("CreatureId")
                        .IsUnique();

                    b.HasIndex("FeetId")
                        .IsUnique();

                    b.HasIndex("HandsId")
                        .IsUnique();

                    b.HasIndex("HeadId")
                        .IsUnique();

                    b.HasIndex("LeftRingId")
                        .IsUnique();

                    b.HasIndex("MainHandId")
                        .IsUnique();

                    b.HasIndex("NeckId")
                        .IsUnique();

                    b.HasIndex("OffHandId")
                        .IsUnique();

                    b.HasIndex("RightRingId")
                        .IsUnique();

                    b.HasIndex("WaistId")
                        .IsUnique();

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId")
                        .IsUnique();

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Life", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("LifeTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("LifeTemplateId");

                    b.ToTable("Lifes");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.MinorSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MinorSkillTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("MinorSkillTemplateId");

                    b.HasIndex("SkillId");

                    b.ToTable("MinorSkills");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("SkillTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("CreatureId");

                    b.HasIndex("SkillTemplateId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Damages.Entities.DamageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignTemplateId");

                    b.ToTable("DamageTypes");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.Configurations.ItemConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArmorPropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BasicAttackTargetFirstLifeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BasicAttackTargetSecondLifeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MeleeHeavyWeaponDamagePropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MeleeHeavyWeaponHitPropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MeleeLightWeaponDamagePropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MeleeLightWeaponHitPropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MeleeMediumWeaponDamagePropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MeleeMediumWeaponHitPropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RangedHeavyWeaponDamagePropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RangedHeavyWeaponHitPropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RangedLightWeaponDamagePropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RangedLightWeaponHitPropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RangedMediumWeaponDamagePropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RangedMediumWeaponHitPropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignTemplateId")
                        .IsUnique();

                    b.ToTable("ItemConfigurations");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid?>("PowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("PowerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("ItemInstances");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.Templates.ItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid?>("PowerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("PowerId");

                    b.ToTable("ItemTemplates");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Powers.Entities.PowerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsedCharges")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("PowerInstance");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Powers.Entities.PowerTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("CastDescription")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CastFormula")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("PowerDurationType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetDefenseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageType")
                        .HasColumnType("integer");

                    b.Property<string>("UsagesFormula")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid?>("UseAttributeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("PowerTemplates");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Rolls.Entities.Roll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfCriticalFailures")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfCriticalSuccesses")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfDices")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfSuccesses")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<int>("RollBonus")
                        .HasColumnType("integer");

                    b.Property<string>("RolledDices")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("Rolls");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Scenes.Entities.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignScenes");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Scenes.Entities.SceneAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneActions");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Scenes.Entities.SceneCreature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreatureCategory")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneCreatures");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.AttributeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignTemplateId");

                    b.ToTable("AttributeTemplates");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchetypeTitle")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CreatureTypeTitle")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("TotalAttributePoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSkillsPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CampaignTemplates");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.DefenseTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatureTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignTemplateId");

                    b.ToTable("DefenseTemplates");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.LifeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatureTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignTemplateId");

                    b.ToTable("LifeTemplates");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.MinorSkillTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("SkillTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("SkillTemplateId");

                    b.ToTable("MinorSkillTemplates");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.SkillTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttributeTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeTemplateId");

                    b.HasIndex("CampaignTemplateId");

                    b.ToTable("SkillTemplates");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.Templates.ArmorTemplate", b =>
                {
                    b.HasBaseType("RoleRollsPocketEdition.Itens.Templates.ItemTemplate");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.Templates.ConsumableTemplate", b =>
                {
                    b.HasBaseType("RoleRollsPocketEdition.Itens.Templates.ItemTemplate");

                    b.HasDiscriminator().HasValue("Consumable");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.Templates.WeaponTemplate", b =>
                {
                    b.HasBaseType("RoleRollsPocketEdition.Itens.Templates.ItemTemplate");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("DamageType")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.ToTable("ItemTemplates", t =>
                        {
                            t.Property("Category")
                                .HasColumnName("WeaponTemplate_Category");
                        });

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Bonuses.Bonus", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Archetypes.Archetype", null)
                        .WithMany("Bonuses")
                        .HasForeignKey("ArchetypeId");

                    b.HasOne("RoleRollsPocketEdition.Roles.Role", null)
                        .WithMany("Bonuses")
                        .HasForeignKey("RoleId");

                    b.OwnsOne("RoleRollsPocketEdition.Core.Entities.Property", "Property", b1 =>
                        {
                            b1.Property<Guid>("BonusId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("IdProperty")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("BonusId");

                            b1.ToTable("Bonus");

                            b1.WithOwner()
                                .HasForeignKey("BonusId");
                        });

                    b.Navigation("Property")
                        .IsRequired();
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Campaigns.Entities.Campaign", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", "CampaignTemplate")
                        .WithMany("Campaigns")
                        .HasForeignKey("CampaignTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Campaigns.Entities.CampaignPlayer", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Campaigns.Entities.Campaign", null)
                        .WithMany("CampaignPlayers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Attribute", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.AttributeTemplate", "AttributeTemplate")
                        .WithMany("Attributes")
                        .HasForeignKey("AttributeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Creature", "Creature")
                        .WithMany("Attributes")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeTemplate");

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.CreaturePower", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Creature", "Creature")
                        .WithMany("Powers")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoleRollsPocketEdition.Powers.Entities.PowerTemplate", "PowerTemplate")
                        .WithMany()
                        .HasForeignKey("PowerTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");

                    b.Navigation("PowerTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Defense", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Creature", null)
                        .WithMany("Defenses")
                        .HasForeignKey("CreatureId");

                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.DefenseTemplate", "DefenseTemplate")
                        .WithMany("Defenses")
                        .HasForeignKey("DefenseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefenseTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Equipment", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "Arms")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "ArmsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "Chest")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "ChestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Creature", "Creature")
                        .WithOne("Equipment")
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "Feet")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "FeetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "Hands")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "HandsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "Head")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "HeadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "LeftRing")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "LeftRingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "MainHand")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "MainHandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "Neck")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "NeckId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "OffHand")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "OffHandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "RightRing")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "RightRingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Itens.ItemInstance", "Waist")
                        .WithOne()
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Equipment", "WaistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Arms");

                    b.Navigation("Chest");

                    b.Navigation("Creature");

                    b.Navigation("Feet");

                    b.Navigation("Hands");

                    b.Navigation("Head");

                    b.Navigation("LeftRing");

                    b.Navigation("MainHand");

                    b.Navigation("Neck");

                    b.Navigation("OffHand");

                    b.Navigation("RightRing");

                    b.Navigation("Waist");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Inventory", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Creature", "Creature")
                        .WithOne("Inventory")
                        .HasForeignKey("RoleRollsPocketEdition.Creatures.Entities.Inventory", "CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Life", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Creature", null)
                        .WithMany("Lifes")
                        .HasForeignKey("CreatureId");

                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.LifeTemplate", "LifeTemplate")
                        .WithMany("Lifes")
                        .HasForeignKey("LifeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LifeTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.MinorSkill", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Creature", null)
                        .WithMany("MinorSkills")
                        .HasForeignKey("CreatureId");

                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.MinorSkillTemplate", "MinorSkillTemplate")
                        .WithMany("MinorSkills")
                        .HasForeignKey("MinorSkillTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Skill", null)
                        .WithMany("MinorSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinorSkillTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Skill", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Attribute", "Attribute")
                        .WithMany("Skills")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Creature", null)
                        .WithMany("Skills")
                        .HasForeignKey("CreatureId");

                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.SkillTemplate", "SkillTemplate")
                        .WithMany("Skills")
                        .HasForeignKey("SkillTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("SkillTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Damages.Entities.DamageType", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", null)
                        .WithMany("DamageTypes")
                        .HasForeignKey("CampaignTemplateId");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.Configurations.ItemConfiguration", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", "CampaignTemplate")
                        .WithOne("ItemConfiguration")
                        .HasForeignKey("RoleRollsPocketEdition.Itens.Configurations.ItemConfiguration", "CampaignTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.ItemInstance", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Creatures.Entities.Inventory", null)
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoleRollsPocketEdition.Powers.Entities.PowerTemplate", "Power")
                        .WithMany()
                        .HasForeignKey("PowerId");

                    b.HasOne("RoleRollsPocketEdition.Itens.Templates.ItemTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Power");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Itens.Templates.ItemTemplate", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Campaigns.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("RoleRollsPocketEdition.Powers.Entities.PowerTemplate", "Power")
                        .WithMany()
                        .HasForeignKey("PowerId");

                    b.Navigation("Campaign");

                    b.Navigation("Power");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Powers.Entities.PowerInstance", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Powers.Entities.PowerTemplate", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Powers.Entities.PowerTemplate", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Campaigns.Entities.Campaign", "Campaign")
                        .WithMany("PowerTemplates")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Rolls.Entities.Roll", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Scenes.Entities.Scene", "Scene")
                        .WithMany("Rolls")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Scenes.Entities.Scene", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Campaigns.Entities.Campaign", "Campaign")
                        .WithMany("Scenes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Scenes.Entities.SceneAction", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Scenes.Entities.Scene", null)
                        .WithMany("Actions")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Scenes.Entities.SceneCreature", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Scenes.Entities.Scene", "Scene")
                        .WithMany("Creatures")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.AttributeTemplate", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", null)
                        .WithMany("Attributes")
                        .HasForeignKey("CampaignTemplateId");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.DefenseTemplate", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", "CampaignTemplate")
                        .WithMany("Defenses")
                        .HasForeignKey("CampaignTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.LifeTemplate", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", "CampaignTemplate")
                        .WithMany("Lifes")
                        .HasForeignKey("CampaignTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.MinorSkillTemplate", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.AttributeTemplate", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId");

                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.SkillTemplate", "SkillTemplate")
                        .WithMany("MinorSkills")
                        .HasForeignKey("SkillTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("SkillTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.SkillTemplate", b =>
                {
                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.AttributeTemplate", "AttributeTemplate")
                        .WithMany("SkillTemplates")
                        .HasForeignKey("AttributeTemplateId");

                    b.HasOne("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", null)
                        .WithMany("AttributelessSkills")
                        .HasForeignKey("CampaignTemplateId");

                    b.Navigation("AttributeTemplate");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Archetypes.Archetype", b =>
                {
                    b.Navigation("Bonuses");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Campaigns.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignPlayers");

                    b.Navigation("PowerTemplates");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Attribute", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Creature", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Defenses");

                    b.Navigation("Equipment")
                        .IsRequired();

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Lifes");

                    b.Navigation("MinorSkills");

                    b.Navigation("Powers");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Creatures.Entities.Skill", b =>
                {
                    b.Navigation("MinorSkills");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Powers.Entities.PowerTemplate", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Roles.Role", b =>
                {
                    b.Navigation("Bonuses");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Scenes.Entities.Scene", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Creatures");

                    b.Navigation("Rolls");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.AttributeTemplate", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("SkillTemplates");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.CampaignTemplate", b =>
                {
                    b.Navigation("AttributelessSkills");

                    b.Navigation("Attributes");

                    b.Navigation("Campaigns");

                    b.Navigation("DamageTypes");

                    b.Navigation("Defenses");

                    b.Navigation("ItemConfiguration")
                        .IsRequired();

                    b.Navigation("Lifes");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.DefenseTemplate", b =>
                {
                    b.Navigation("Defenses");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.LifeTemplate", b =>
                {
                    b.Navigation("Lifes");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.MinorSkillTemplate", b =>
                {
                    b.Navigation("MinorSkills");
                });

            modelBuilder.Entity("RoleRollsPocketEdition.Templates.Entities.SkillTemplate", b =>
                {
                    b.Navigation("MinorSkills");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
